### ISSUE TITLE
vuetify not detecting it.

### ISSUE THREAD

**Issue by Adeelasd** [JackPu/vue-core-video-player#7]
This dependency was not found:

* vue-core-video-player in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/vuetify-loader/lib/loader.js??ref--17-0!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/News/videos.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save vue-core-video-player

**Comment by JackPu** [comment]
@Adeelasd Thanks a lot.

The package is not ready now. It is still in the developing stage. And I'll fix your issue soon.
